### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by RAMSHEER** [spotify/ios-sdk#179]
Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      -[SPTSessionManager initWithConfiguration:PKCEProvider:delegate:] in SpotifyiOS(SPTSessionManager.o)
      -[SPTSessionManager initiateSessionWithScope:options:] in SpotifyiOS(SPTSessionManager.o)
      -[SPTSessionManager initiateSessionWithScope:options:presentingViewController:] in SpotifyiOS(SPTSessionManager.o)
      -[SPTSessionManager initiateDefaultSessionWithAuthorizationURL:] in SpotifyiOS(SPTSessionManager.o)
      -[SPTSessionManager initiateClientSessionWithAuthorizationURL:] in SpotifyiOS(SPTSessionManager.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am getting this error when I tried running the demo program and also integrating the project. please help

**Comment by mxcl** [comment]
Happens with Xcode 11 if targeting iOS 13. Which means it is impossible to build SwiftUI Spotify apps with libspotify :/

**Comment by cjam** [comment]
I'm seeing this same error on my CI build, but only when I upgraded the SDK from v1.0.0 to version 1.2.0. @RAMSHEER Did you figure out how to fix it?

**Comment by cjam** [comment]
I've been trying to fix this on and off for a few days.  I found this issue https://github.com/stripe/stripe-ios/issues/1288 and cross-referenced it with the commit history to find this commit https://github.com/stripe/stripe-ios/pull/1305 which seems like it could have something to do with the settings that were used to compile the framework?  Seems weird to me though that I can build it on my machine but fails in CI.  

Will continue to investigate.  If anyone has any ideas I am all ears.

**Comment by cjam** [comment]
I did a little bit more investigating.  Found this thread https://forums.developer.apple.com/thread/123003 indicating that frameworks built with XCode 11 and `___isPlatformVersionAtLeast` are not compatible with XCode 10.  I switched my CI build to use XCode 11 and it fixed the problem.

Perhaps the requirement of XCode 11 should be mentioned as a requirement in this repos `ReadMe`

**Comment by ImKateryna** [comment]
I'm building in XCODE 11 and still have this issue :(

**Comment by kkarayannis** [comment]
Version v1.2.1, released just now, removes the need for the `-Objc` flag in `Other linker flags`.
It has been suggested that this is a potential workaround for this issue. Let me know if this works for you.

**Comment by kkarayannis** [comment]
We've released version v1.2.2 that should fix this issue for everyone. Please us know if it's still an issue.

**Comment by cjam** [comment]
My issue was solved by moving over from XCode 10 to XCode 11.  But thanks for the additional fix.

**Comment by Joesta** [comment]
Hi, i seem to be having the same issue with xcode 10.1.

Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      -[UIView(GMSSafeAreaSupport) gms_safeAreaInsets] in GoogleMaps
      -[GMSScreenInfo initWithUIScreen:] in GoogleMaps
      -[GMSx_QTMCollectionViewController viewDidLoad] in GoogleMaps
      -[GMSx_QTMCollectionViewController viewDidLayoutSubviews] in GoogleMaps
      -[GMSx_QTMCollectionViewStyleController contentViewInsetsForCellWithAttribute:] in GoogleMaps
      -[GMSx_QTMCollectionViewStyleController setInsetsContentViewsToSafeArea:] in GoogleMaps
      -[GMSx_QTMCollectionViewStyleController insetsAtSectionIndex:] in GoogleMaps

I have been trying to solve this error for days now. Anyone with an idea, please help. Thank you.
